spring:
  application:
    name: graphql-client-service
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
feign:
  circuitbreaker:
    enabled: true