spring:
  application:
    name: manufacturer-service
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: bitnami
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true